model_2:
  Model_Best_params:
    ccp_alpha: 0.0002554469016080299
    criterion: friedman_mse
    learning_rate: 0.07873530371672265
    loss: exponential
    max_depth: 10
    max_features: sqrt
    min_impurity_decrease: 0.3728250003759186
    min_samples_leaf: 10
    min_samples_split: 6
    min_weight_fraction_leaf: 0.021766625775714817
    n_estimators: 359
    subsample: 0.6643841227812608
    tol: 0.008522979742345177
  Model_Best_params_score: 0.777070144231101
  Model_class: GradientBoostingClassifier
  Model_module: sklearn.ensemble
  training_artifact_file_path: artifact\stage04_model_training\model_eval_reports\gbt_study.csv
model_3:
  Model_Best_params:
    bagging_fraction: 0.9
    bagging_freq: 5
    feature_fraction: 0.5
    lambda_l1: 10.0
    lambda_l2: 50.0
    learning_rate: 0.024864850611373387
    max_depth: 10
    min_data_in_leaf: 8
    min_gain_to_split: 0.0
    n_estimators: 824
    num_leaves: 101
  Model_Best_params_score: 0.7790566013650093
  Model_class: LGBMClassifier
  Model_module: lightgbm
  training_artifact_file_path: artifact\stage04_model_training\model_eval_reports\lgbt_study.csv
model_5:
  Model_Best_params:
    bootstrap: true
    criterion: entropy
    max_depth: 9
    max_leaf_nodes: 10
    min_samples_leaf: 2
    n_estimators: 676
  Model_Best_params_score: 0.7635910764865594
  Model_class: RandomForestClassifier
  Model_module: sklearn.ensemble
  training_artifact_file_path: artifact\stage04_model_training\model_eval_reports\xgboost_study.csv
model_6:
  Model_Best_params:
    bootstrap: true
    criterion: entropy
    max_depth: 10
    max_leaf_nodes: 10
    min_samples_leaf: 4
    n_estimators: 118
  Model_Best_params_score: 0.76359408166489
  Model_class: CatBoostClassifier
  Model_module: catboost
  training_artifact_file_path: artifact\stage04_model_training\model_eval_reports\catboost_study.csv
