model_2:
  Model_Best_params:
    ccp_alpha: 0.00021878723670504198
    criterion: friedman_mse
    learning_rate: 0.012264008116924015
    loss: exponential
    max_depth: 6
    max_features: sqrt
    min_impurity_decrease: 0.17207083394984396
    min_samples_leaf: 8
    min_samples_split: 9
    min_weight_fraction_leaf: 0.000237231167255585
    n_estimators: 979
    subsample: 0.9877254326015861
    tol: 0.008585113030861725
  Model_Best_params_score: 0.7783075038245431
  Model_class: GradientBoostingClassifier
  Model_module: sklearn.ensemble
  training_artifact_file_path: artifact\stage04_model_training\model_eval_reports\gbt_study.csv
model_3:
  Model_Best_params:
    bagging_fraction: 0.9
    bagging_freq: 5
    feature_fraction: 0.5
    lambda_l1: 10.0
    lambda_l2: 50.0
    learning_rate: 0.024864850611373387
    max_depth: 10
    min_data_in_leaf: 8
    min_gain_to_split: 0.0
    n_estimators: 824
    num_leaves: 101
  Model_Best_params_score: 0.7790566013650093
  Model_class: LGBMClassifier
  Model_module: lightgbm
  training_artifact_file_path: artifact\stage04_model_training\model_eval_reports\lgbt_study.csv
model_5:
  Model_Best_params:
    bootstrap: true
    criterion: entropy
    max_depth: 9
    max_leaf_nodes: 10
    min_samples_leaf: 4
    n_estimators: 329
  Model_Best_params_score: 0.7638120531082309
  Model_class: RandomForestClassifier
  Model_module: sklearn.ensemble
  training_artifact_file_path: artifact\stage04_model_training\model_eval_reports\xgboost_study.csv
model_6:
  Model_Best_params:
    bootstrap: true
    criterion: entropy
    max_depth: 8
    max_leaf_nodes: 10
    min_samples_leaf: 3
    n_estimators: 146
  Model_Best_params_score: 0.7639171954481602
  Model_class: CatBoostClassifier
  Model_module: catboost
  training_artifact_file_path: artifact\stage04_model_training\model_eval_reports\catboost_study.csv
